[package]
name = "frost-blueprint"
version = "0.2.0"
edition = "2021"
description = "FROST Blueprint built using Tangle Gadget SDK"
authors = ["Webb Technologies Inc."]
license = "Unlicense"
homepage = "https://github.com/tangle-network/frost-blueprint"
repository = "https://github.com/tangle-network/frost-blueprint"
readme = "README.md"
categories = ["cryptography", "cryptography::cryptocurrencies"]
keywords = ["tangle", "blueprint", "avs"]
rust-version = "1.81"

[lib]
path = "src/lib.rs"

[[bin]]
name = "frost-blueprint"
path = "src/main.rs"

[package.metadata.blueprint]
manager = { Evm = "FrostBlueprint" }

# [[package.metadata.gadget.Native.sources]]
# owner = "tangle-network"
# repo = "frost-blueprint"
# tag = "0.1.0"
# binaries = [
#     { arch = "Arm64", os = "Macos", name = "frost-blueprint-aarch64-apple-darwin.tar.xz" },
#     { arch = "Amd64", os = "Macos", name = "frost-blueprint-x86_64-apple-darwin.tar.xz" },
#     { arch = "Amd64", os = "Macos", name = "frost-blueprint-x86_64-unknown-linux-gnu.tar.xz" },
# ]

[dependencies]
tracing = "0.1"
thiserror = "2.0"
displaydoc = "0.2.5"
async-trait = "0.1"
futures = "0.3"
color-eyre = { version = "0.6", features = ["tracing-error", "color-spantrace"] }
hex = "0.4"
k256 = { version = "0.13.4" }
tokio = { version = "^1", default-features = false, features = ["full", "rt-multi-thread"] }
tokio-stream = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3", features = ["parking_lot", "env-filter"] }
serde = { version = "^1", default-features = false, features = ["alloc"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
rand = "0.8"
rand_chacha = { version = "0.3", default-features = false }

# FROST
frost-core = { version = "2.1", default-features = false, features = ["serialization", "cheater-detection"] }
frost-ed25519 = { version = "2.1", default-features = false, features = ["serialization", "cheater-detection"] }
frost-secp256k1 = { version = "2.1", default-features = false, features = ["serialization", "cheater-detection"] }

sled = { version = "0.34", default-features = false, optional = true }
round-based = { version = "0.3.0", default-features = false, features = ["derive"] }

blueprint-sdk = { git = "https://github.com/tangle-network/gadget.git", features = [
    "macros",
    "tangle",
    "networking",
    "local-store",
    "networking-sp-core-ecdsa",
] }


[dev-dependencies]
tokio = { version = "^1", default-features = false, features = ["full", "rt-multi-thread"] }
frost-core = { version = "2.0", default-features = false, features = [
    "serialization",
    "cheater-detection",
    "internals",
] }
round-based = { version = "0.3.0", default-features = false, features = ["derive", "dev"] }
proptest = { version = "1.5.0", default-features = false, features = ["std", "bit-set", "fork", "timeout"] }
test-strategy = { version = "0.4.0", default-features = false }

blueprint-sdk = { git = "https://github.com/tangle-network/gadget.git", features = ["std", "tangle", "testing"] }

[build-dependencies]
blueprint-sdk = { git = "https://github.com/tangle-network/gadget.git", features = ["build"] }

[features]
default = ["std", "kv-sled"]
std = [
    "blueprint-sdk/std",
    "frost-core/std",
    "frost-ed25519/std",
    "frost-secp256k1/std",
    "serde_json/std",
    "serde/std",
    "rand_chacha/std",
]
kv-sled = ["sled"]
kv-mem = []

# Internal features for end-to-end tests
e2e = []

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
